Comment out debugging echo's, and cleanup

diff --git a/loadwatch b/loadwatch
--- a/loadwatch
+++ b/loadwatch
@@ -47,11 +47,9 @@ IFS=$'\n\t'
 # Change these two variables to override the defaults.
 # Load Threshold for doing a dump. Default is 50% of CPU for physical servers and a load average of 8 for virtual servers.
 THRESH= 
-# <- Set to 0 so always generates a log for testing. - Alex Kr
 #echo "DEBUG: THRESH=${THRESH}" 1>&2
-# Memory threshold for doing a dump. Default is...
+# Memory threshold for doing a dump. Default is 50% used MEM.
 MEM_THRESH= 
-# <- Set to 0 so always triggers when testing. - Alex Kr
 #echo "DEBUG: MEM_THRESH=${MEM_THRESH}" 1>&2
 # Retention duration of log files. Default is 14 days.
 RETEN=
@@ -300,7 +298,7 @@ main() {
   fi
 
   # Written this way is allows comparison of decimal numbers.
-#echo "DEBUG: LOAD Expression evaluates to: $(echo "${LOAD} > ${THRESH}" | bc -l)" 1>&2
+#echo "DEBUG: LOAD expression evaluates to: $(echo "${LOAD} > ${THRESH}" | bc -l)" 1>&2
 #echo "DEBUG: MEM expression evaluates to: $(echo "${MEM} > ${MEM_THRESH}" | bc -l)" 1>&2
   if (( $(echo "${LOAD} > ${THRESH}" | bc -l) )); then
 #echo "DEBUG: THRESH is < LOAD." 1>&2
@@ -316,7 +314,7 @@ main() {
   cleanup_files
 }
 
-case ${1-default} in  # Set a default expansion to avoid failures in bash hard-mode
+case ${1-default} in  # Set a default expansion to avoid failures in bash strict-mode
   update)
     echo "Running LoadWatch manual update..."
     wget -O $DIR/loadwatch ${RAWURL}
