v1.2.0
-Corrected a report formatting in "checklog".
-Fixed an issue in the `cleanup_files` function.
-Changed the default thresholds for virtual machines.
-Added the Auto Update feature.
-Added the ability to run `loadwatch update` to manually update the file.

diff --git a/loadwatch b/loadwatch
--- a/loadwatch
+++ b/loadwatch
@@ -2,7 +2,7 @@
 
 # CREDIT
 # Originally written by jonathonrox24 (https://github.com/jonathonrox24)
-# Udated by Hummdis (hummdis.com).
+# Updated by Hummdis (hummdis.com).
 
 # LICENSE
 # Released under the Apache License 2.0.
@@ -43,14 +43,18 @@
 THRESH=
 # Retention duration of log files. Default is 14 days.
 RETEN=
+# By default, LoadWatch auto-updates. To turn this off, change this to "false".
+AUTO_UPDATE="false"
+
 
 ########################################################################
 # NO MORE CHANGES BELOW THIS POINT, UNLESS YOU KNOW WHAT YOU'RE DOING. #
 ########################################################################
 
 # Variables
-VERSION=1.1.9
-DATE=$(date +%F.%k:%M)
+VERSION=1.2.0
+NEW_VER=$(curl -sL https://raw.githubusercontent.com/Hummdis/loadwatch/master/loadwatch | grep "VERSION=" | cut -d = -f 2)
+DATE=$(date +%F.%H:%M)
 LOAD=$(cat /proc/loadavg | awk '{print $1}')
 FILE=loadwatch_${DATE}_Load.${LOAD}.txt
 DIR=/root/loadwatch
@@ -64,7 +68,7 @@ fi
 
 # Gather the system stats and put them into the log.
 dump_stats() {
-    echo -e "\tALERT: Loadwatch Triggered! - ${DATE} - Load: (${LOAD}) - Log: ${DIR}/${FILE}" >> $DIR/$LOG
+    echo -e "ALERT: Loadwatch Triggered! - Timestamp: ${DATE} - Load: ${LOAD} - Log: ${DIR}/${FILE}" >> $DIR/$LOG
     echo -e "=-=-=-=-=-=    BEGIN LOADWATCH REPORT - ${VERSION}  =-=-=-=-=-=\n" > $DIR/$FILE
 	echo $DATE >> $DIR/$FILE
 	echo $LOAD >> $DIR/$FILE
@@ -82,7 +86,7 @@ dump_stats() {
     netstat -tn 2>/dev/null | grep :80 | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -nr | head >> $DIR/$FILE
 	echo -e "\n${DIVIDER}\n" >> $DIR/$FILE
 	echo "TOP STATUS" >> $DIR/$FILE
-    top -bcn1 >> $DIR/$FILE
+    top -bcn 1 >> $DIR/$FILE
 	echo -e "\n${DIVIDER}\n" >> $DIR/$FILE
 	echo "PROCESS LIST" >> $DIR/$FILE
     ps auxf >> $DIR/$FILE
@@ -100,19 +104,16 @@ cleanup_files() {
     if [ -z "${RETEN}" ]; then
         RETEN=14
     fi
-    cd ${DIR}
-    find ${DIR} -name loadwatch_* -mtime +${RETEN} -exec rm -f {} \;
+    find $DIR -name 'loadwatch_*' -mtime +$RETEN -exec rm -f {} \;
 	
 	# Rotate the 'checklog' file every 24 hours and compress it.  Then, delete any older than the retention period.
-	LINES=$(cat ${DIR}/checklog | wc -l)
-	if [ $(date +%H%M) == 0000 ] && [ ${LINES} -lt 15 ]; then
+	if [ $(date +%H%M) == 0000 ]; then
 		NEWLOG=${DIR}/${LOG}.$(date -d "yesterday" +%Y-%m-%d)
 		mv $LOG $NEWLOG
 		touch $LOG
 		gzip -f -9 ${NEWLOG}
 	fi
-	cd $DIR
-	find ${DIR} -type f -name checklog.* -mtime +$RETEN -exec rm -f {} \;
+	find $DIR -type f -name '${LOG.}*' -mtime +$RETEN -exec rm -f {} \;
 }
 
 # Check for facter, needed to determine if system is physical or virtual. Abort if it's missing.
@@ -149,12 +150,71 @@ lscpu_check() {
 	fi
 }
 
+# Check for updates to LoadWatch
+update_check() {
+    # This will return the following numbers for the two arguments passed.
+    # 0 if $1 = $2
+    # 1 if $1 > $2
+    # 2 if $1 < $2
+
+    if [[ $1 == $2 ]]; then
+        return 0
+    fi
+
+    local IFS=.
+    local i ver1=($1) ver2=($2)
+    # Fill empty fields in ver1 with zeros
+    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
+        ver1[i]=0
+    done
+
+    for ((i=0; i<${#ver1[@]}; i++)); do
+        if [[ -z ${ver2[i]} ]]; then
+            # Fill empty fields in ver2 with zeros
+            ver2[i]=0
+        fi
+
+        if ((10#${ver1[i]} > 10#${ver2[i]})); then
+            return 1
+        fi
+
+        if ((10#${ver1[i]} < 10#${ver2[i]})); then
+            return 2
+        fi
+    done
+
+    return 0
+}
+
 # Main process.
 main() {
-	echo "Loadwatch check: ${DATE} - Load: ${LOAD}" >> ${DIR}/checklog
+	echo "LoadWatch v${VERSION} - Timestamp: ${DATE} - Load: ${LOAD}" >> $DIR/$LOG
+
+    # Perform update check.
+    update_check ${NEW_VER} ${VERSION}
+    case $? in
+        0)  # No update available. Do nothing.
+            ;;
+        1)  # If Auto Update is enabled, update. Otherwise, report a new version, but do nothing else.
+            if [[$AUTO_UPDATE == "true" ]]; then
+                echo "Update Check - Auto Update enabled.  Updating to v${NEW_VER}" >> $DIR/$LOG
+                wget -O $DIR/loadwatch https://raw.githubusercontent.com/Hummdis/loadwatch/master/loadwatch && chmod +x $DIR/loadwatch
+            else
+                echo "Update Check - LoadWatch v${NEW_VER} available. Auto Update disabled." >> $DIR/$LOG
+            fi
+            ;;
+        2)  # The public version is older than the current version.
+            echo "Update Check - Running LoadWatch version is ${VERSION}, but published version is ${NEW_VER}. Is this a pre-release?" >> $DIR/$LOG
+            ;;
+        *)  # All other values are invalid. Report, but don't cause the program to abort.
+            echo "Update Check - LoadWatch Update Check returned an invalid code ($?). Skipping update." >> $DIR/$LOG
+            ;;
+    esac
+
+    # Perform the actual work.
 	if [ -z "${THRESH}" ]; then
 		if [ virtual_check ]; then
-			MAX=16
+			MAX=5
 		elif [ lscpu_check ]; then
 			MAX=$(lscpu | grep "per socket:" | awk '{print $4}')
 		else
@@ -162,13 +222,25 @@ main() {
 		fi
 		THRESH=$(expr $MAX / 2)
 	fi
-	# Changing this actually allows comparison of decimal numbers.
+	
+    # Written this way is allows comparison of decimal numbers.
 	if (( $(echo "${LOAD} > ${THRESH}" | bc -l) )); then
 		dump_stats
-		cleanup_files
 	fi
+    
+    # Always perform cleaup to keep with retention settings.
+    cleanup_files
 }
 
-main
+case $1 in
+    update)
+        echo "Running LoadWatch manual update..."
+        wget -O $DIR/loadwatch https://raw.githubusercontent.com/Hummdis/loadwatch/master/loadwatch && chmod +x $DIR/loadwatch
+        echo "LoadWatch update complete."
+        ;;
+    *)
+        main
+        ;;
+esac
 
 exit 0
